services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./volumes/pgdata:/var/lib/postgresql/data"
    networks:
      - ${GLOBAL_NETWORK:-kafka}